language: php

php:
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm

services:
  - memcached
  - redis-server

script:
  #- mkdir -p build/logs
  - vendor/bin/phpunit
  #--coverage-clover build/logs/clover.xml

before_script:
  #- mysql -e 'CREATE DATABASE titon_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

after_script:
  #- mysql -e 'DROP DATABASE titon_test;'
  #- php vendor/bin/coveralls -v

notifications:
  email: false
